/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AttendanceLogDataTable: typeof import('./src/components/datatables/AttendanceLogDataTable.vue')['default']
    AudigLogDataTable: typeof import('./src/components/datatables/AudigLogDataTable.vue')['default']
    AuditLogSummaryList: typeof import('./src/components/AuditLogSummaryList.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    ClassAttendanceSummaryList: typeof import('./src/components/ClassAttendanceSummaryList.vue')['default']
    ClassManagementDataTable: typeof import('./src/components/datatables/ClassManagementDataTable.vue')['default']
    ClassMeetingList: typeof import('./src/components/ClassMeetingList.vue')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    CourseManagementDataTable: typeof import('./src/components/datatables/CourseManagementDataTable.vue')['default']
    CreateClassDialog: typeof import('./src/components/dialogs/CreateClassDialog.vue')['default']
    CreateEditCourseDialog: typeof import('./src/components/dialogs/CreateEditCourseDialog.vue')['default']
    CreateEditStudentDialog: typeof import('./src/components/dialogs/CreateEditStudentDialog.vue')['default']
    CreateMeetingDialog: typeof import('./src/components/dialogs/CreateMeetingDialog.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DataView: typeof import('primevue/dataview')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    DistributionMetricCard: typeof import('./src/components/DistributionMetricCard.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    EditClassForm: typeof import('./src/components/forms/EditClassForm.vue')['default']
    GetStudentsDialog: typeof import('./src/components/dialogs/GetStudentsDialog.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    ImportStudentsDialog: typeof import('./src/components/dialogs/ImportStudentsDialog.vue')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputLabel: typeof import('./src/components/InputLabel.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LineChart: typeof import('./src/components/charts/LineChart.vue')['default']
    MeetingCard: typeof import('./src/components/MeetingCard.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Message: typeof import('primevue/message')['default']
    MetricCard: typeof import('./src/components/MetricCard.vue')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    Password: typeof import('primevue/password')['default']
    PlaceholderItem: typeof import('./src/components/PlaceholderItem.vue')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollPanel: typeof import('primevue/scrollpanel')['default']
    ScrollTop: typeof import('primevue/scrolltop')['default']
    Select: typeof import('primevue/select')['default']
    StudentManagementDataTable: typeof import('./src/components/datatables/StudentManagementDataTable.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    ThemeSwitcher: typeof import('./src/components/ThemeSwitcher.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    UserManagementDataTable: typeof import('./src/components/datatables/UserManagementDataTable.vue')['default']
    ViewMeetingAttendance: typeof import('./src/components/dialogs/ViewMeetingAttendance.vue')['default']
    YearLevelBarChart: typeof import('./src/components/charts/YearLevelBarChart.vue')['default']
  }
  export interface GlobalDirectives {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
